// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldwbngdiktorluwaxzcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkd2JuZ2Rpa3Rvcmx1d2F4emNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjAzNDgsImV4cCI6MjA2NjMzNjM0OH0.PgwT4A1niMwMYFEp6j2hlGKP9zIwE7UKdu67SvhlV8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);